/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebzineRouteImport } from './routes/webzine'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as ProgrammeTvRouteImport } from './routes/programme-tv'
import { Route as PartenariatsRouteImport } from './routes/partenariats'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InfosOfficiellesRouteImport } from './routes/infos-officielles'
import { Route as FlashInfoRouteImport } from './routes/flash-info'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebzineIndexRouteImport } from './routes/webzine.index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as WebzineSlugRouteImport } from './routes/webzine.$slug'
import { Route as TvDirectRouteImport } from './routes/tv.direct'
import { Route as EmissionsSlugRouteImport } from './routes/emissions.$slug'
import { Route as TvEmissionsSlugRouteImport } from './routes/tv.emissions.$slug'

const WebzineRoute = WebzineRouteImport.update({
  id: '/webzine',
  path: '/webzine',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeTvRoute = ProgrammeTvRouteImport.update({
  id: '/programme-tv',
  path: '/programme-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenariatsRoute = PartenariatsRouteImport.update({
  id: '/partenariats',
  path: '/partenariats',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosOfficiellesRoute = InfosOfficiellesRouteImport.update({
  id: '/infos-officielles',
  path: '/infos-officielles',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashInfoRoute = FlashInfoRouteImport.update({
  id: '/flash-info',
  path: '/flash-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebzineIndexRoute = WebzineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebzineRoute,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TvRoute,
} as any)
const WebzineSlugRoute = WebzineSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WebzineRoute,
} as any)
const TvDirectRoute = TvDirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => TvRoute,
} as any)
const EmissionsSlugRoute = EmissionsSlugRouteImport.update({
  id: '/emissions/$slug',
  path: '/emissions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TvEmissionsSlugRoute = TvEmissionsSlugRouteImport.update({
  id: '/emissions/$slug',
  path: '/emissions/$slug',
  getParentRoute: () => TvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flash-info': typeof FlashInfoRoute
  '/infos-officielles': typeof InfosOfficiellesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenariats': typeof PartenariatsRoute
  '/programme-tv': typeof ProgrammeTvRoute
  '/radio': typeof RadioRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRouteWithChildren
  '/webzine': typeof WebzineRouteWithChildren
  '/emissions/$slug': typeof EmissionsSlugRoute
  '/tv/direct': typeof TvDirectRoute
  '/webzine/$slug': typeof WebzineSlugRoute
  '/tv/': typeof TvIndexRoute
  '/webzine/': typeof WebzineIndexRoute
  '/tv/emissions/$slug': typeof TvEmissionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flash-info': typeof FlashInfoRoute
  '/infos-officielles': typeof InfosOfficiellesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenariats': typeof PartenariatsRoute
  '/programme-tv': typeof ProgrammeTvRoute
  '/radio': typeof RadioRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emissions/$slug': typeof EmissionsSlugRoute
  '/tv/direct': typeof TvDirectRoute
  '/webzine/$slug': typeof WebzineSlugRoute
  '/tv': typeof TvIndexRoute
  '/webzine': typeof WebzineIndexRoute
  '/tv/emissions/$slug': typeof TvEmissionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flash-info': typeof FlashInfoRoute
  '/infos-officielles': typeof InfosOfficiellesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenariats': typeof PartenariatsRoute
  '/programme-tv': typeof ProgrammeTvRoute
  '/radio': typeof RadioRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRouteWithChildren
  '/webzine': typeof WebzineRouteWithChildren
  '/emissions/$slug': typeof EmissionsSlugRoute
  '/tv/direct': typeof TvDirectRoute
  '/webzine/$slug': typeof WebzineSlugRoute
  '/tv/': typeof TvIndexRoute
  '/webzine/': typeof WebzineIndexRoute
  '/tv/emissions/$slug': typeof TvEmissionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/flash-info'
    | '/infos-officielles'
    | '/mentions-legales'
    | '/partenariats'
    | '/programme-tv'
    | '/radio'
    | '/recherche'
    | '/sitemap.xml'
    | '/tv'
    | '/webzine'
    | '/emissions/$slug'
    | '/tv/direct'
    | '/webzine/$slug'
    | '/tv/'
    | '/webzine/'
    | '/tv/emissions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/flash-info'
    | '/infos-officielles'
    | '/mentions-legales'
    | '/partenariats'
    | '/programme-tv'
    | '/radio'
    | '/recherche'
    | '/sitemap.xml'
    | '/emissions/$slug'
    | '/tv/direct'
    | '/webzine/$slug'
    | '/tv'
    | '/webzine'
    | '/tv/emissions/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/flash-info'
    | '/infos-officielles'
    | '/mentions-legales'
    | '/partenariats'
    | '/programme-tv'
    | '/radio'
    | '/recherche'
    | '/sitemap.xml'
    | '/tv'
    | '/webzine'
    | '/emissions/$slug'
    | '/tv/direct'
    | '/webzine/$slug'
    | '/tv/'
    | '/webzine/'
    | '/tv/emissions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FlashInfoRoute: typeof FlashInfoRoute
  InfosOfficiellesRoute: typeof InfosOfficiellesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenariatsRoute: typeof PartenariatsRoute
  ProgrammeTvRoute: typeof ProgrammeTvRoute
  RadioRoute: typeof RadioRoute
  RechercheRoute: typeof RechercheRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TvRoute: typeof TvRouteWithChildren
  WebzineRoute: typeof WebzineRouteWithChildren
  EmissionsSlugRoute: typeof EmissionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webzine': {
      id: '/webzine'
      path: '/webzine'
      fullPath: '/webzine'
      preLoaderRoute: typeof WebzineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme-tv': {
      id: '/programme-tv'
      path: '/programme-tv'
      fullPath: '/programme-tv'
      preLoaderRoute: typeof ProgrammeTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenariats': {
      id: '/partenariats'
      path: '/partenariats'
      fullPath: '/partenariats'
      preLoaderRoute: typeof PartenariatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos-officielles': {
      id: '/infos-officielles'
      path: '/infos-officielles'
      fullPath: '/infos-officielles'
      preLoaderRoute: typeof InfosOfficiellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-info': {
      id: '/flash-info'
      path: '/flash-info'
      fullPath: '/flash-info'
      preLoaderRoute: typeof FlashInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webzine/': {
      id: '/webzine/'
      path: '/'
      fullPath: '/webzine/'
      preLoaderRoute: typeof WebzineIndexRouteImport
      parentRoute: typeof WebzineRoute
    }
    '/tv/': {
      id: '/tv/'
      path: '/'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof TvRoute
    }
    '/webzine/$slug': {
      id: '/webzine/$slug'
      path: '/$slug'
      fullPath: '/webzine/$slug'
      preLoaderRoute: typeof WebzineSlugRouteImport
      parentRoute: typeof WebzineRoute
    }
    '/tv/direct': {
      id: '/tv/direct'
      path: '/direct'
      fullPath: '/tv/direct'
      preLoaderRoute: typeof TvDirectRouteImport
      parentRoute: typeof TvRoute
    }
    '/emissions/$slug': {
      id: '/emissions/$slug'
      path: '/emissions/$slug'
      fullPath: '/emissions/$slug'
      preLoaderRoute: typeof EmissionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/emissions/$slug': {
      id: '/tv/emissions/$slug'
      path: '/emissions/$slug'
      fullPath: '/tv/emissions/$slug'
      preLoaderRoute: typeof TvEmissionsSlugRouteImport
      parentRoute: typeof TvRoute
    }
  }
}

interface TvRouteChildren {
  TvDirectRoute: typeof TvDirectRoute
  TvIndexRoute: typeof TvIndexRoute
  TvEmissionsSlugRoute: typeof TvEmissionsSlugRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvDirectRoute: TvDirectRoute,
  TvIndexRoute: TvIndexRoute,
  TvEmissionsSlugRoute: TvEmissionsSlugRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

interface WebzineRouteChildren {
  WebzineSlugRoute: typeof WebzineSlugRoute
  WebzineIndexRoute: typeof WebzineIndexRoute
}

const WebzineRouteChildren: WebzineRouteChildren = {
  WebzineSlugRoute: WebzineSlugRoute,
  WebzineIndexRoute: WebzineIndexRoute,
}

const WebzineRouteWithChildren =
  WebzineRoute._addFileChildren(WebzineRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FlashInfoRoute: FlashInfoRoute,
  InfosOfficiellesRoute: InfosOfficiellesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenariatsRoute: PartenariatsRoute,
  ProgrammeTvRoute: ProgrammeTvRoute,
  RadioRoute: RadioRoute,
  RechercheRoute: RechercheRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TvRoute: TvRouteWithChildren,
  WebzineRoute: WebzineRouteWithChildren,
  EmissionsSlugRoute: EmissionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
