/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebzineRouteImport } from './routes/webzine'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as ProgrammeTvRouteImport } from './routes/programme-tv'
import { Route as PartenariatsRouteImport } from './routes/partenariats'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InfosOfficiellesRouteImport } from './routes/infos-officielles'
import { Route as FlashInfoRouteImport } from './routes/flash-info'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebzineIndexRouteImport } from './routes/webzine.index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as WebzineSlugRouteImport } from './routes/webzine.$slug'
import { Route as TvDirectRouteImport } from './routes/tv.direct'
import { Route as EmissionsSlugRouteImport } from './routes/emissions.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthedRouteImport } from './routes/admin._authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin._authed.index'
import { Route as TvEmissionsSlugRouteImport } from './routes/tv.emissions.$slug'
import { Route as AdminAuthedStreamsRouteImport } from './routes/admin._authed.streams'
import { Route as AdminAuthedReplaysRouteImport } from './routes/admin._authed.replays'
import { Route as AdminAuthedProgrammeRouteImport } from './routes/admin._authed.programme'
import { Route as AdminAuthedPodcastsRouteImport } from './routes/admin._authed.podcasts'
import { Route as AdminAuthedFlashInfoRouteImport } from './routes/admin._authed.flash-info'
import { Route as AdminAuthedEmissionsRouteImport } from './routes/admin._authed.emissions'
import { Route as AdminAuthedArticlesRouteImport } from './routes/admin._authed.articles'

const WebzineRoute = WebzineRouteImport.update({
  id: '/webzine',
  path: '/webzine',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeTvRoute = ProgrammeTvRouteImport.update({
  id: '/programme-tv',
  path: '/programme-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenariatsRoute = PartenariatsRouteImport.update({
  id: '/partenariats',
  path: '/partenariats',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosOfficiellesRoute = InfosOfficiellesRouteImport.update({
  id: '/infos-officielles',
  path: '/infos-officielles',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashInfoRoute = FlashInfoRouteImport.update({
  id: '/flash-info',
  path: '/flash-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebzineIndexRoute = WebzineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebzineRoute,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TvRoute,
} as any)
const WebzineSlugRoute = WebzineSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WebzineRoute,
} as any)
const TvDirectRoute = TvDirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => TvRoute,
} as any)
const EmissionsSlugRoute = EmissionsSlugRouteImport.update({
  id: '/emissions/$slug',
  path: '/emissions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const TvEmissionsSlugRoute = TvEmissionsSlugRouteImport.update({
  id: '/emissions/$slug',
  path: '/emissions/$slug',
  getParentRoute: () => TvRoute,
} as any)
const AdminAuthedStreamsRoute = AdminAuthedStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedReplaysRoute = AdminAuthedReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProgrammeRoute = AdminAuthedProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedPodcastsRoute = AdminAuthedPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedFlashInfoRoute = AdminAuthedFlashInfoRouteImport.update({
  id: '/flash-info',
  path: '/flash-info',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedEmissionsRoute = AdminAuthedEmissionsRouteImport.update({
  id: '/emissions',
  path: '/emissions',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedArticlesRoute = AdminAuthedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flash-info': typeof FlashInfoRoute
  '/infos-officielles': typeof InfosOfficiellesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenariats': typeof PartenariatsRoute
  '/programme-tv': typeof ProgrammeTvRoute
  '/radio': typeof RadioRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRouteWithChildren
  '/webzine': typeof WebzineRouteWithChildren
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/emissions/$slug': typeof EmissionsSlugRoute
  '/tv/direct': typeof TvDirectRoute
  '/webzine/$slug': typeof WebzineSlugRoute
  '/tv/': typeof TvIndexRoute
  '/webzine/': typeof WebzineIndexRoute
  '/admin/articles': typeof AdminAuthedArticlesRoute
  '/admin/emissions': typeof AdminAuthedEmissionsRoute
  '/admin/flash-info': typeof AdminAuthedFlashInfoRoute
  '/admin/podcasts': typeof AdminAuthedPodcastsRoute
  '/admin/programme': typeof AdminAuthedProgrammeRoute
  '/admin/replays': typeof AdminAuthedReplaysRoute
  '/admin/streams': typeof AdminAuthedStreamsRoute
  '/tv/emissions/$slug': typeof TvEmissionsSlugRoute
  '/admin/': typeof AdminAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flash-info': typeof FlashInfoRoute
  '/infos-officielles': typeof InfosOfficiellesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenariats': typeof PartenariatsRoute
  '/programme-tv': typeof ProgrammeTvRoute
  '/radio': typeof RadioRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/emissions/$slug': typeof EmissionsSlugRoute
  '/tv/direct': typeof TvDirectRoute
  '/webzine/$slug': typeof WebzineSlugRoute
  '/tv': typeof TvIndexRoute
  '/webzine': typeof WebzineIndexRoute
  '/admin/articles': typeof AdminAuthedArticlesRoute
  '/admin/emissions': typeof AdminAuthedEmissionsRoute
  '/admin/flash-info': typeof AdminAuthedFlashInfoRoute
  '/admin/podcasts': typeof AdminAuthedPodcastsRoute
  '/admin/programme': typeof AdminAuthedProgrammeRoute
  '/admin/replays': typeof AdminAuthedReplaysRoute
  '/admin/streams': typeof AdminAuthedStreamsRoute
  '/tv/emissions/$slug': typeof TvEmissionsSlugRoute
  '/admin': typeof AdminAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flash-info': typeof FlashInfoRoute
  '/infos-officielles': typeof InfosOfficiellesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenariats': typeof PartenariatsRoute
  '/programme-tv': typeof ProgrammeTvRoute
  '/radio': typeof RadioRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRouteWithChildren
  '/webzine': typeof WebzineRouteWithChildren
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/emissions/$slug': typeof EmissionsSlugRoute
  '/tv/direct': typeof TvDirectRoute
  '/webzine/$slug': typeof WebzineSlugRoute
  '/tv/': typeof TvIndexRoute
  '/webzine/': typeof WebzineIndexRoute
  '/admin/_authed/articles': typeof AdminAuthedArticlesRoute
  '/admin/_authed/emissions': typeof AdminAuthedEmissionsRoute
  '/admin/_authed/flash-info': typeof AdminAuthedFlashInfoRoute
  '/admin/_authed/podcasts': typeof AdminAuthedPodcastsRoute
  '/admin/_authed/programme': typeof AdminAuthedProgrammeRoute
  '/admin/_authed/replays': typeof AdminAuthedReplaysRoute
  '/admin/_authed/streams': typeof AdminAuthedStreamsRoute
  '/tv/emissions/$slug': typeof TvEmissionsSlugRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/flash-info'
    | '/infos-officielles'
    | '/mentions-legales'
    | '/partenariats'
    | '/programme-tv'
    | '/radio'
    | '/recherche'
    | '/sitemap.xml'
    | '/tv'
    | '/webzine'
    | '/admin'
    | '/admin/login'
    | '/emissions/$slug'
    | '/tv/direct'
    | '/webzine/$slug'
    | '/tv/'
    | '/webzine/'
    | '/admin/articles'
    | '/admin/emissions'
    | '/admin/flash-info'
    | '/admin/podcasts'
    | '/admin/programme'
    | '/admin/replays'
    | '/admin/streams'
    | '/tv/emissions/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/flash-info'
    | '/infos-officielles'
    | '/mentions-legales'
    | '/partenariats'
    | '/programme-tv'
    | '/radio'
    | '/recherche'
    | '/sitemap.xml'
    | '/admin/login'
    | '/emissions/$slug'
    | '/tv/direct'
    | '/webzine/$slug'
    | '/tv'
    | '/webzine'
    | '/admin/articles'
    | '/admin/emissions'
    | '/admin/flash-info'
    | '/admin/podcasts'
    | '/admin/programme'
    | '/admin/replays'
    | '/admin/streams'
    | '/tv/emissions/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/flash-info'
    | '/infos-officielles'
    | '/mentions-legales'
    | '/partenariats'
    | '/programme-tv'
    | '/radio'
    | '/recherche'
    | '/sitemap.xml'
    | '/tv'
    | '/webzine'
    | '/admin/_authed'
    | '/admin/login'
    | '/emissions/$slug'
    | '/tv/direct'
    | '/webzine/$slug'
    | '/tv/'
    | '/webzine/'
    | '/admin/_authed/articles'
    | '/admin/_authed/emissions'
    | '/admin/_authed/flash-info'
    | '/admin/_authed/podcasts'
    | '/admin/_authed/programme'
    | '/admin/_authed/replays'
    | '/admin/_authed/streams'
    | '/tv/emissions/$slug'
    | '/admin/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FlashInfoRoute: typeof FlashInfoRoute
  InfosOfficiellesRoute: typeof InfosOfficiellesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenariatsRoute: typeof PartenariatsRoute
  ProgrammeTvRoute: typeof ProgrammeTvRoute
  RadioRoute: typeof RadioRoute
  RechercheRoute: typeof RechercheRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TvRoute: typeof TvRouteWithChildren
  WebzineRoute: typeof WebzineRouteWithChildren
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  EmissionsSlugRoute: typeof EmissionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webzine': {
      id: '/webzine'
      path: '/webzine'
      fullPath: '/webzine'
      preLoaderRoute: typeof WebzineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme-tv': {
      id: '/programme-tv'
      path: '/programme-tv'
      fullPath: '/programme-tv'
      preLoaderRoute: typeof ProgrammeTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenariats': {
      id: '/partenariats'
      path: '/partenariats'
      fullPath: '/partenariats'
      preLoaderRoute: typeof PartenariatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos-officielles': {
      id: '/infos-officielles'
      path: '/infos-officielles'
      fullPath: '/infos-officielles'
      preLoaderRoute: typeof InfosOfficiellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-info': {
      id: '/flash-info'
      path: '/flash-info'
      fullPath: '/flash-info'
      preLoaderRoute: typeof FlashInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webzine/': {
      id: '/webzine/'
      path: '/'
      fullPath: '/webzine/'
      preLoaderRoute: typeof WebzineIndexRouteImport
      parentRoute: typeof WebzineRoute
    }
    '/tv/': {
      id: '/tv/'
      path: '/'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof TvRoute
    }
    '/webzine/$slug': {
      id: '/webzine/$slug'
      path: '/$slug'
      fullPath: '/webzine/$slug'
      preLoaderRoute: typeof WebzineSlugRouteImport
      parentRoute: typeof WebzineRoute
    }
    '/tv/direct': {
      id: '/tv/direct'
      path: '/direct'
      fullPath: '/tv/direct'
      preLoaderRoute: typeof TvDirectRouteImport
      parentRoute: typeof TvRoute
    }
    '/emissions/$slug': {
      id: '/emissions/$slug'
      path: '/emissions/$slug'
      fullPath: '/emissions/$slug'
      preLoaderRoute: typeof EmissionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/tv/emissions/$slug': {
      id: '/tv/emissions/$slug'
      path: '/emissions/$slug'
      fullPath: '/tv/emissions/$slug'
      preLoaderRoute: typeof TvEmissionsSlugRouteImport
      parentRoute: typeof TvRoute
    }
    '/admin/_authed/streams': {
      id: '/admin/_authed/streams'
      path: '/streams'
      fullPath: '/admin/streams'
      preLoaderRoute: typeof AdminAuthedStreamsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/replays': {
      id: '/admin/_authed/replays'
      path: '/replays'
      fullPath: '/admin/replays'
      preLoaderRoute: typeof AdminAuthedReplaysRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/programme': {
      id: '/admin/_authed/programme'
      path: '/programme'
      fullPath: '/admin/programme'
      preLoaderRoute: typeof AdminAuthedProgrammeRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/podcasts': {
      id: '/admin/_authed/podcasts'
      path: '/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AdminAuthedPodcastsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/flash-info': {
      id: '/admin/_authed/flash-info'
      path: '/flash-info'
      fullPath: '/admin/flash-info'
      preLoaderRoute: typeof AdminAuthedFlashInfoRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/emissions': {
      id: '/admin/_authed/emissions'
      path: '/emissions'
      fullPath: '/admin/emissions'
      preLoaderRoute: typeof AdminAuthedEmissionsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/articles': {
      id: '/admin/_authed/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminAuthedArticlesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface TvRouteChildren {
  TvDirectRoute: typeof TvDirectRoute
  TvIndexRoute: typeof TvIndexRoute
  TvEmissionsSlugRoute: typeof TvEmissionsSlugRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvDirectRoute: TvDirectRoute,
  TvIndexRoute: TvIndexRoute,
  TvEmissionsSlugRoute: TvEmissionsSlugRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

interface WebzineRouteChildren {
  WebzineSlugRoute: typeof WebzineSlugRoute
  WebzineIndexRoute: typeof WebzineIndexRoute
}

const WebzineRouteChildren: WebzineRouteChildren = {
  WebzineSlugRoute: WebzineSlugRoute,
  WebzineIndexRoute: WebzineIndexRoute,
}

const WebzineRouteWithChildren =
  WebzineRoute._addFileChildren(WebzineRouteChildren)

interface AdminAuthedRouteChildren {
  AdminAuthedArticlesRoute: typeof AdminAuthedArticlesRoute
  AdminAuthedEmissionsRoute: typeof AdminAuthedEmissionsRoute
  AdminAuthedFlashInfoRoute: typeof AdminAuthedFlashInfoRoute
  AdminAuthedPodcastsRoute: typeof AdminAuthedPodcastsRoute
  AdminAuthedProgrammeRoute: typeof AdminAuthedProgrammeRoute
  AdminAuthedReplaysRoute: typeof AdminAuthedReplaysRoute
  AdminAuthedStreamsRoute: typeof AdminAuthedStreamsRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedArticlesRoute: AdminAuthedArticlesRoute,
  AdminAuthedEmissionsRoute: AdminAuthedEmissionsRoute,
  AdminAuthedFlashInfoRoute: AdminAuthedFlashInfoRoute,
  AdminAuthedPodcastsRoute: AdminAuthedPodcastsRoute,
  AdminAuthedProgrammeRoute: AdminAuthedProgrammeRoute,
  AdminAuthedReplaysRoute: AdminAuthedReplaysRoute,
  AdminAuthedStreamsRoute: AdminAuthedStreamsRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FlashInfoRoute: FlashInfoRoute,
  InfosOfficiellesRoute: InfosOfficiellesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenariatsRoute: PartenariatsRoute,
  ProgrammeTvRoute: ProgrammeTvRoute,
  RadioRoute: RadioRoute,
  RechercheRoute: RechercheRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TvRoute: TvRouteWithChildren,
  WebzineRoute: WebzineRouteWithChildren,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  EmissionsSlugRoute: EmissionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
